//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Final_Assessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public string MessageTitle { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
    }
}
